// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_bgmCompare_parallel
Rcpp::List run_bgmCompare_parallel(const arma::imat& observations, int num_groups, const std::vector<arma::imat>& counts_per_category, const std::vector<arma::imat>& blume_capel_stats, const std::vector<arma::mat>& pairwise_stats, const arma::ivec& num_categories, double main_alpha, double main_beta, double pairwise_scale, const arma::mat& pairwise_scaling_factors, double difference_scale, double difference_selection_alpha, double difference_selection_beta, const std::string& difference_prior, int iter, int warmup, bool na_impute, const arma::imat& missing_data_indices, const arma::uvec& is_ordinal_variable, const arma::ivec& baseline_category, bool difference_selection, bool main_difference_selection, const arma::imat& main_effect_indices, const arma::imat& pairwise_effect_indices, double target_accept, int nuts_max_depth, bool learn_mass_matrix, const arma::mat& projection, const arma::ivec& group_membership, const arma::imat& group_indices, const arma::imat& interaction_index_matrix, const arma::mat& inclusion_probability, int num_chains, int nThreads, int seed, const std::string& update_method, int hmc_num_leapfrogs, int progress_type);
RcppExport SEXP _bgms_run_bgmCompare_parallel(SEXP observationsSEXP, SEXP num_groupsSEXP, SEXP counts_per_categorySEXP, SEXP blume_capel_statsSEXP, SEXP pairwise_statsSEXP, SEXP num_categoriesSEXP, SEXP main_alphaSEXP, SEXP main_betaSEXP, SEXP pairwise_scaleSEXP, SEXP pairwise_scaling_factorsSEXP, SEXP difference_scaleSEXP, SEXP difference_selection_alphaSEXP, SEXP difference_selection_betaSEXP, SEXP difference_priorSEXP, SEXP iterSEXP, SEXP warmupSEXP, SEXP na_imputeSEXP, SEXP missing_data_indicesSEXP, SEXP is_ordinal_variableSEXP, SEXP baseline_categorySEXP, SEXP difference_selectionSEXP, SEXP main_difference_selectionSEXP, SEXP main_effect_indicesSEXP, SEXP pairwise_effect_indicesSEXP, SEXP target_acceptSEXP, SEXP nuts_max_depthSEXP, SEXP learn_mass_matrixSEXP, SEXP projectionSEXP, SEXP group_membershipSEXP, SEXP group_indicesSEXP, SEXP interaction_index_matrixSEXP, SEXP inclusion_probabilitySEXP, SEXP num_chainsSEXP, SEXP nThreadsSEXP, SEXP seedSEXP, SEXP update_methodSEXP, SEXP hmc_num_leapfrogsSEXP, SEXP progress_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::imat>& >::type counts_per_category(counts_per_categorySEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::imat>& >::type blume_capel_stats(blume_capel_statsSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type pairwise_stats(pairwise_statsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< double >::type main_alpha(main_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type main_beta(main_betaSEXP);
    Rcpp::traits::input_parameter< double >::type pairwise_scale(pairwise_scaleSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_scaling_factors(pairwise_scaling_factorsSEXP);
    Rcpp::traits::input_parameter< double >::type difference_scale(difference_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type difference_selection_alpha(difference_selection_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type difference_selection_beta(difference_selection_betaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type difference_prior(difference_priorSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type missing_data_indices(missing_data_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type is_ordinal_variable(is_ordinal_variableSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< bool >::type difference_selection(difference_selectionSEXP);
    Rcpp::traits::input_parameter< bool >::type main_difference_selection(main_difference_selectionSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type main_effect_indices(main_effect_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pairwise_effect_indices(pairwise_effect_indicesSEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type nuts_max_depth(nuts_max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type learn_mass_matrix(learn_mass_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type projection(projectionSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_membership(group_membershipSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type group_indices(group_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type interaction_index_matrix(interaction_index_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type inclusion_probability(inclusion_probabilitySEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type update_method(update_methodSEXP);
    Rcpp::traits::input_parameter< int >::type hmc_num_leapfrogs(hmc_num_leapfrogsSEXP);
    Rcpp::traits::input_parameter< int >::type progress_type(progress_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_bgmCompare_parallel(observations, num_groups, counts_per_category, blume_capel_stats, pairwise_stats, num_categories, main_alpha, main_beta, pairwise_scale, pairwise_scaling_factors, difference_scale, difference_selection_alpha, difference_selection_beta, difference_prior, iter, warmup, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, difference_selection, main_difference_selection, main_effect_indices, pairwise_effect_indices, target_accept, nuts_max_depth, learn_mass_matrix, projection, group_membership, group_indices, interaction_index_matrix, inclusion_probability, num_chains, nThreads, seed, update_method, hmc_num_leapfrogs, progress_type));
    return rcpp_result_gen;
END_RCPP
}
// get_explog_switch
Rcpp::String get_explog_switch();
RcppExport SEXP _bgms_get_explog_switch() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_explog_switch());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ieee754_exp
Rcpp::NumericVector rcpp_ieee754_exp(Rcpp::NumericVector x);
RcppExport SEXP _bgms_rcpp_ieee754_exp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ieee754_exp(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ieee754_log
Rcpp::NumericVector rcpp_ieee754_log(Rcpp::NumericVector x);
RcppExport SEXP _bgms_rcpp_ieee754_log(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ieee754_log(x));
    return rcpp_result_gen;
END_RCPP
}
// compute_ess_cpp
Rcpp::NumericVector compute_ess_cpp(Rcpp::NumericVector array3d);
RcppExport SEXP _bgms_compute_ess_cpp(SEXP array3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type array3d(array3dSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ess_cpp(array3d));
    return rcpp_result_gen;
END_RCPP
}
// compute_rhat_cpp
Rcpp::NumericVector compute_rhat_cpp(Rcpp::NumericVector array3d);
RcppExport SEXP _bgms_compute_rhat_cpp(SEXP array3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type array3d(array3dSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rhat_cpp(array3d));
    return rcpp_result_gen;
END_RCPP
}
// compute_indicator_ess_cpp
Rcpp::NumericMatrix compute_indicator_ess_cpp(Rcpp::NumericVector array3d);
RcppExport SEXP _bgms_compute_indicator_ess_cpp(SEXP array3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type array3d(array3dSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_indicator_ess_cpp(array3d));
    return rcpp_result_gen;
END_RCPP
}
// compute_conditional_ggm
Rcpp::List compute_conditional_ggm(const arma::mat& observations, const arma::ivec& predict_vars, const arma::mat& precision);
RcppExport SEXP _bgms_compute_conditional_ggm(SEXP observationsSEXP, SEXP predict_varsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type predict_vars(predict_varsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_conditional_ggm(observations, predict_vars, precision));
    return rcpp_result_gen;
END_RCPP
}
// compute_conditional_probs
Rcpp::List compute_conditional_probs(arma::imat observations, arma::ivec predict_vars, arma::mat pairwise, arma::mat main, arma::ivec num_categories, Rcpp::StringVector variable_type, arma::ivec baseline_category);
RcppExport SEXP _bgms_compute_conditional_probs(SEXP observationsSEXP, SEXP predict_varsSEXP, SEXP pairwiseSEXP, SEXP mainSEXP, SEXP num_categoriesSEXP, SEXP variable_typeSEXP, SEXP baseline_categorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type predict_vars(predict_varsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pairwise(pairwiseSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type main(mainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type variable_type(variable_typeSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type baseline_category(baseline_categorySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_conditional_probs(observations, predict_vars, pairwise, main, num_categories, variable_type, baseline_category));
    return rcpp_result_gen;
END_RCPP
}
// compute_conditional_mixed
Rcpp::List compute_conditional_mixed(const arma::imat& x_observations, const arma::mat& y_observations, const arma::ivec& predict_vars, const arma::mat& pairwise_disc, const arma::mat& pairwise_cross, const arma::mat& pairwise_cont, const arma::mat& mux, const arma::vec& muy, const arma::ivec& num_categories, const Rcpp::StringVector& variable_type, const arma::ivec& baseline_category);
RcppExport SEXP _bgms_compute_conditional_mixed(SEXP x_observationsSEXP, SEXP y_observationsSEXP, SEXP predict_varsSEXP, SEXP pairwise_discSEXP, SEXP pairwise_crossSEXP, SEXP pairwise_contSEXP, SEXP muxSEXP, SEXP muySEXP, SEXP num_categoriesSEXP, SEXP variable_typeSEXP, SEXP baseline_categorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type x_observations(x_observationsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_observations(y_observationsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type predict_vars(predict_varsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_disc(pairwise_discSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_cross(pairwise_crossSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_cont(pairwise_contSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mux(muxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type muy(muySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type variable_type(variable_typeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_conditional_mixed(x_observations, y_observations, predict_vars, pairwise_disc, pairwise_cross, pairwise_cont, mux, muy, num_categories, variable_type, baseline_category));
    return rcpp_result_gen;
END_RCPP
}
// sample_omrf_gibbs
IntegerMatrix sample_omrf_gibbs(int num_states, int num_variables, IntegerVector num_categories, NumericMatrix pairwise, NumericMatrix main, int iter, int seed);
RcppExport SEXP _bgms_sample_omrf_gibbs(SEXP num_statesSEXP, SEXP num_variablesSEXP, SEXP num_categoriesSEXP, SEXP pairwiseSEXP, SEXP mainSEXP, SEXP iterSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< int >::type num_variables(num_variablesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pairwise(pairwiseSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type main(mainSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_omrf_gibbs(num_states, num_variables, num_categories, pairwise, main, iter, seed));
    return rcpp_result_gen;
END_RCPP
}
// sample_bcomrf_gibbs
IntegerMatrix sample_bcomrf_gibbs(int num_states, int num_variables, IntegerVector num_categories, NumericMatrix pairwise, NumericMatrix main, StringVector variable_type_r, IntegerVector baseline_category, int iter, int seed);
RcppExport SEXP _bgms_sample_bcomrf_gibbs(SEXP num_statesSEXP, SEXP num_variablesSEXP, SEXP num_categoriesSEXP, SEXP pairwiseSEXP, SEXP mainSEXP, SEXP variable_type_rSEXP, SEXP baseline_categorySEXP, SEXP iterSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< int >::type num_variables(num_variablesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pairwise(pairwiseSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type main(mainSEXP);
    Rcpp::traits::input_parameter< StringVector >::type variable_type_r(variable_type_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_bcomrf_gibbs(num_states, num_variables, num_categories, pairwise, main, variable_type_r, baseline_category, iter, seed));
    return rcpp_result_gen;
END_RCPP
}
// sample_ggm_direct
NumericMatrix sample_ggm_direct(int num_states, NumericMatrix precision, NumericVector means, int seed);
RcppExport SEXP _bgms_sample_ggm_direct(SEXP num_statesSEXP, SEXP precisionSEXP, SEXP meansSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ggm_direct(num_states, precision, means, seed));
    return rcpp_result_gen;
END_RCPP
}
// run_simulation_parallel
Rcpp::List run_simulation_parallel(const arma::mat& pairwise_samples, const arma::mat& main_samples, const arma::ivec& draw_indices, int num_states, int num_variables, const arma::ivec& num_categories, const Rcpp::StringVector& variable_type_r, const arma::ivec& baseline_category, int iter, int nThreads, int seed, int progress_type);
RcppExport SEXP _bgms_run_simulation_parallel(SEXP pairwise_samplesSEXP, SEXP main_samplesSEXP, SEXP draw_indicesSEXP, SEXP num_statesSEXP, SEXP num_variablesSEXP, SEXP num_categoriesSEXP, SEXP variable_type_rSEXP, SEXP baseline_categorySEXP, SEXP iterSEXP, SEXP nThreadsSEXP, SEXP seedSEXP, SEXP progress_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_samples(pairwise_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type main_samples(main_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type draw_indices(draw_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< int >::type num_variables(num_variablesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type variable_type_r(variable_type_rSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type progress_type(progress_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_simulation_parallel(pairwise_samples, main_samples, draw_indices, num_states, num_variables, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type));
    return rcpp_result_gen;
END_RCPP
}
// run_ggm_simulation_parallel
Rcpp::List run_ggm_simulation_parallel(const arma::mat& pairwise_samples, const arma::mat& main_samples, const arma::ivec& draw_indices, int num_states, int num_variables, const arma::vec& means, int nThreads, int seed, int progress_type);
RcppExport SEXP _bgms_run_ggm_simulation_parallel(SEXP pairwise_samplesSEXP, SEXP main_samplesSEXP, SEXP draw_indicesSEXP, SEXP num_statesSEXP, SEXP num_variablesSEXP, SEXP meansSEXP, SEXP nThreadsSEXP, SEXP seedSEXP, SEXP progress_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pairwise_samples(pairwise_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type main_samples(main_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type draw_indices(draw_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< int >::type num_variables(num_variablesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type progress_type(progress_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_ggm_simulation_parallel(pairwise_samples, main_samples, draw_indices, num_states, num_variables, means, nThreads, seed, progress_type));
    return rcpp_result_gen;
END_RCPP
}
// sample_mixed_mrf_gibbs
Rcpp::List sample_mixed_mrf_gibbs(int num_states, NumericMatrix pairwise_disc_r, NumericMatrix pairwise_cross_r, NumericMatrix pairwise_cont_r, NumericMatrix mux_r, NumericVector muy_r, IntegerVector num_categories_r, Rcpp::StringVector variable_type_r, IntegerVector baseline_category_r, int iter, int seed);
RcppExport SEXP _bgms_sample_mixed_mrf_gibbs(SEXP num_statesSEXP, SEXP pairwise_disc_rSEXP, SEXP pairwise_cross_rSEXP, SEXP pairwise_cont_rSEXP, SEXP mux_rSEXP, SEXP muy_rSEXP, SEXP num_categories_rSEXP, SEXP variable_type_rSEXP, SEXP baseline_category_rSEXP, SEXP iterSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pairwise_disc_r(pairwise_disc_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pairwise_cross_r(pairwise_cross_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pairwise_cont_r(pairwise_cont_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mux_r(mux_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muy_r(muy_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_categories_r(num_categories_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type variable_type_r(variable_type_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type baseline_category_r(baseline_category_rSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_mixed_mrf_gibbs(num_states, pairwise_disc_r, pairwise_cross_r, pairwise_cont_r, mux_r, muy_r, num_categories_r, variable_type_r, baseline_category_r, iter, seed));
    return rcpp_result_gen;
END_RCPP
}
// run_mixed_simulation_parallel
Rcpp::List run_mixed_simulation_parallel(const arma::mat& mux_samples, const arma::mat& disc_samples, const arma::mat& muy_samples, const arma::mat& cont_samples, const arma::mat& cross_samples, const arma::ivec& draw_indices, int num_states, int p, int q, const arma::ivec& num_categories, const Rcpp::StringVector& variable_type_r, const arma::ivec& baseline_category, int iter, int nThreads, int seed, int progress_type);
RcppExport SEXP _bgms_run_mixed_simulation_parallel(SEXP mux_samplesSEXP, SEXP disc_samplesSEXP, SEXP muy_samplesSEXP, SEXP cont_samplesSEXP, SEXP cross_samplesSEXP, SEXP draw_indicesSEXP, SEXP num_statesSEXP, SEXP pSEXP, SEXP qSEXP, SEXP num_categoriesSEXP, SEXP variable_type_rSEXP, SEXP baseline_categorySEXP, SEXP iterSEXP, SEXP nThreadsSEXP, SEXP seedSEXP, SEXP progress_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mux_samples(mux_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type disc_samples(disc_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type muy_samples(muy_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cont_samples(cont_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cross_samples(cross_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type draw_indices(draw_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_categories(num_categoriesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type variable_type_r(variable_type_rSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type baseline_category(baseline_categorySEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type progress_type(progress_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mixed_simulation_parallel(mux_samples, disc_samples, muy_samples, cont_samples, cross_samples, draw_indices, num_states, p, q, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type));
    return rcpp_result_gen;
END_RCPP
}
// sample_ggm
Rcpp::List sample_ggm(const Rcpp::List& inputFromR, const arma::mat& prior_inclusion_prob, const arma::imat& initial_edge_indicators, const int no_iter, const int no_warmup, const int no_chains, const bool edge_selection, const int seed, const int no_threads, const int progress_type, const std::string& edge_prior, const double beta_bernoulli_alpha, const double beta_bernoulli_beta, const double beta_bernoulli_alpha_between, const double beta_bernoulli_beta_between, const double dirichlet_alpha, const double lambda, const bool na_impute, const Rcpp::Nullable<Rcpp::IntegerMatrix> missing_index_nullable);
RcppExport SEXP _bgms_sample_ggm(SEXP inputFromRSEXP, SEXP prior_inclusion_probSEXP, SEXP initial_edge_indicatorsSEXP, SEXP no_iterSEXP, SEXP no_warmupSEXP, SEXP no_chainsSEXP, SEXP edge_selectionSEXP, SEXP seedSEXP, SEXP no_threadsSEXP, SEXP progress_typeSEXP, SEXP edge_priorSEXP, SEXP beta_bernoulli_alphaSEXP, SEXP beta_bernoulli_betaSEXP, SEXP beta_bernoulli_alpha_betweenSEXP, SEXP beta_bernoulli_beta_betweenSEXP, SEXP dirichlet_alphaSEXP, SEXP lambdaSEXP, SEXP na_imputeSEXP, SEXP missing_index_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputFromR(inputFromRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_inclusion_prob(prior_inclusion_probSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type initial_edge_indicators(initial_edge_indicatorsSEXP);
    Rcpp::traits::input_parameter< const int >::type no_iter(no_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type no_warmup(no_warmupSEXP);
    Rcpp::traits::input_parameter< const int >::type no_chains(no_chainsSEXP);
    Rcpp::traits::input_parameter< const bool >::type edge_selection(edge_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type no_threads(no_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type progress_type(progress_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type edge_prior(edge_priorSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha(beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta(beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha_between(beta_bernoulli_alpha_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta_between(beta_bernoulli_beta_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerMatrix> >::type missing_index_nullable(missing_index_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ggm(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, na_impute, missing_index_nullable));
    return rcpp_result_gen;
END_RCPP
}
// sample_mixed_mrf
Rcpp::List sample_mixed_mrf(const Rcpp::List& inputFromR, const arma::mat& prior_inclusion_prob, const arma::imat& initial_edge_indicators, const int no_iter, const int no_warmup, const int no_chains, const bool edge_selection, const int seed, const int no_threads, const int progress_type, const std::string& edge_prior, const double beta_bernoulli_alpha, const double beta_bernoulli_beta, const double beta_bernoulli_alpha_between, const double beta_bernoulli_beta_between, const double dirichlet_alpha, const double lambda, const std::string& sampler_type, const double target_acceptance, const int max_tree_depth, const int num_leapfrogs, const bool na_impute, const Rcpp::Nullable<Rcpp::IntegerMatrix> missing_index_discrete_nullable, const Rcpp::Nullable<Rcpp::IntegerMatrix> missing_index_continuous_nullable);
RcppExport SEXP _bgms_sample_mixed_mrf(SEXP inputFromRSEXP, SEXP prior_inclusion_probSEXP, SEXP initial_edge_indicatorsSEXP, SEXP no_iterSEXP, SEXP no_warmupSEXP, SEXP no_chainsSEXP, SEXP edge_selectionSEXP, SEXP seedSEXP, SEXP no_threadsSEXP, SEXP progress_typeSEXP, SEXP edge_priorSEXP, SEXP beta_bernoulli_alphaSEXP, SEXP beta_bernoulli_betaSEXP, SEXP beta_bernoulli_alpha_betweenSEXP, SEXP beta_bernoulli_beta_betweenSEXP, SEXP dirichlet_alphaSEXP, SEXP lambdaSEXP, SEXP sampler_typeSEXP, SEXP target_acceptanceSEXP, SEXP max_tree_depthSEXP, SEXP num_leapfrogsSEXP, SEXP na_imputeSEXP, SEXP missing_index_discrete_nullableSEXP, SEXP missing_index_continuous_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputFromR(inputFromRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_inclusion_prob(prior_inclusion_probSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type initial_edge_indicators(initial_edge_indicatorsSEXP);
    Rcpp::traits::input_parameter< const int >::type no_iter(no_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type no_warmup(no_warmupSEXP);
    Rcpp::traits::input_parameter< const int >::type no_chains(no_chainsSEXP);
    Rcpp::traits::input_parameter< const bool >::type edge_selection(edge_selectionSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type no_threads(no_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type progress_type(progress_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type edge_prior(edge_priorSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha(beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta(beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha_between(beta_bernoulli_alpha_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta_between(beta_bernoulli_beta_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sampler_type(sampler_typeSEXP);
    Rcpp::traits::input_parameter< const double >::type target_acceptance(target_acceptanceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_tree_depth(max_tree_depthSEXP);
    Rcpp::traits::input_parameter< const int >::type num_leapfrogs(num_leapfrogsSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerMatrix> >::type missing_index_discrete_nullable(missing_index_discrete_nullableSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerMatrix> >::type missing_index_continuous_nullable(missing_index_continuous_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_mixed_mrf(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, sampler_type, target_acceptance, max_tree_depth, num_leapfrogs, na_impute, missing_index_discrete_nullable, missing_index_continuous_nullable));
    return rcpp_result_gen;
END_RCPP
}
// sample_omrf
Rcpp::List sample_omrf(const Rcpp::List& inputFromR, const arma::mat& prior_inclusion_prob, const arma::imat& initial_edge_indicators, const int no_iter, const int no_warmup, const int no_chains, const bool edge_selection, const std::string& sampler_type, const int seed, const int no_threads, const int progress_type, const std::string& edge_prior, const bool na_impute, const Rcpp::Nullable<Rcpp::IntegerMatrix> missing_index_nullable, const double beta_bernoulli_alpha, const double beta_bernoulli_beta, const double beta_bernoulli_alpha_between, const double beta_bernoulli_beta_between, const double dirichlet_alpha, const double lambda, const double target_acceptance, const int max_tree_depth, const int num_leapfrogs, const Rcpp::Nullable<Rcpp::NumericMatrix> pairwise_scaling_factors_nullable);
RcppExport SEXP _bgms_sample_omrf(SEXP inputFromRSEXP, SEXP prior_inclusion_probSEXP, SEXP initial_edge_indicatorsSEXP, SEXP no_iterSEXP, SEXP no_warmupSEXP, SEXP no_chainsSEXP, SEXP edge_selectionSEXP, SEXP sampler_typeSEXP, SEXP seedSEXP, SEXP no_threadsSEXP, SEXP progress_typeSEXP, SEXP edge_priorSEXP, SEXP na_imputeSEXP, SEXP missing_index_nullableSEXP, SEXP beta_bernoulli_alphaSEXP, SEXP beta_bernoulli_betaSEXP, SEXP beta_bernoulli_alpha_betweenSEXP, SEXP beta_bernoulli_beta_betweenSEXP, SEXP dirichlet_alphaSEXP, SEXP lambdaSEXP, SEXP target_acceptanceSEXP, SEXP max_tree_depthSEXP, SEXP num_leapfrogsSEXP, SEXP pairwise_scaling_factors_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputFromR(inputFromRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_inclusion_prob(prior_inclusion_probSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type initial_edge_indicators(initial_edge_indicatorsSEXP);
    Rcpp::traits::input_parameter< const int >::type no_iter(no_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type no_warmup(no_warmupSEXP);
    Rcpp::traits::input_parameter< const int >::type no_chains(no_chainsSEXP);
    Rcpp::traits::input_parameter< const bool >::type edge_selection(edge_selectionSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sampler_type(sampler_typeSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type no_threads(no_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type progress_type(progress_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type edge_prior(edge_priorSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_impute(na_imputeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerMatrix> >::type missing_index_nullable(missing_index_nullableSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha(beta_bernoulli_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta(beta_bernoulli_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_alpha_between(beta_bernoulli_alpha_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_bernoulli_beta_between(beta_bernoulli_beta_betweenSEXP);
    Rcpp::traits::input_parameter< const double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type target_acceptance(target_acceptanceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_tree_depth(max_tree_depthSEXP);
    Rcpp::traits::input_parameter< const int >::type num_leapfrogs(num_leapfrogsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericMatrix> >::type pairwise_scaling_factors_nullable(pairwise_scaling_factors_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_omrf(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, sampler_type, seed, no_threads, progress_type, edge_prior, na_impute, missing_index_nullable, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, target_acceptance, max_tree_depth, num_leapfrogs, pairwise_scaling_factors_nullable));
    return rcpp_result_gen;
END_RCPP
}
// compute_Vn_mfm_sbm
arma::vec compute_Vn_mfm_sbm(arma::uword num_variables, double dirichlet_alpha, arma::uword t_max, double lambda);
RcppExport SEXP _bgms_compute_Vn_mfm_sbm(SEXP num_variablesSEXP, SEXP dirichlet_alphaSEXP, SEXP t_maxSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type num_variables(num_variablesSEXP);
    Rcpp::traits::input_parameter< double >::type dirichlet_alpha(dirichlet_alphaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Vn_mfm_sbm(num_variables, dirichlet_alpha, t_max, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bgms_run_bgmCompare_parallel", (DL_FUNC) &_bgms_run_bgmCompare_parallel, 38},
    {"_bgms_get_explog_switch", (DL_FUNC) &_bgms_get_explog_switch, 0},
    {"_bgms_rcpp_ieee754_exp", (DL_FUNC) &_bgms_rcpp_ieee754_exp, 1},
    {"_bgms_rcpp_ieee754_log", (DL_FUNC) &_bgms_rcpp_ieee754_log, 1},
    {"_bgms_compute_ess_cpp", (DL_FUNC) &_bgms_compute_ess_cpp, 1},
    {"_bgms_compute_rhat_cpp", (DL_FUNC) &_bgms_compute_rhat_cpp, 1},
    {"_bgms_compute_indicator_ess_cpp", (DL_FUNC) &_bgms_compute_indicator_ess_cpp, 1},
    {"_bgms_compute_conditional_ggm", (DL_FUNC) &_bgms_compute_conditional_ggm, 3},
    {"_bgms_compute_conditional_probs", (DL_FUNC) &_bgms_compute_conditional_probs, 7},
    {"_bgms_compute_conditional_mixed", (DL_FUNC) &_bgms_compute_conditional_mixed, 11},
    {"_bgms_sample_omrf_gibbs", (DL_FUNC) &_bgms_sample_omrf_gibbs, 7},
    {"_bgms_sample_bcomrf_gibbs", (DL_FUNC) &_bgms_sample_bcomrf_gibbs, 9},
    {"_bgms_sample_ggm_direct", (DL_FUNC) &_bgms_sample_ggm_direct, 4},
    {"_bgms_run_simulation_parallel", (DL_FUNC) &_bgms_run_simulation_parallel, 12},
    {"_bgms_run_ggm_simulation_parallel", (DL_FUNC) &_bgms_run_ggm_simulation_parallel, 9},
    {"_bgms_sample_mixed_mrf_gibbs", (DL_FUNC) &_bgms_sample_mixed_mrf_gibbs, 11},
    {"_bgms_run_mixed_simulation_parallel", (DL_FUNC) &_bgms_run_mixed_simulation_parallel, 16},
    {"_bgms_sample_ggm", (DL_FUNC) &_bgms_sample_ggm, 19},
    {"_bgms_sample_mixed_mrf", (DL_FUNC) &_bgms_sample_mixed_mrf, 24},
    {"_bgms_sample_omrf", (DL_FUNC) &_bgms_sample_omrf, 24},
    {"_bgms_compute_Vn_mfm_sbm", (DL_FUNC) &_bgms_compute_Vn_mfm_sbm, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bgms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
