# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_bgmCompare_parallel <- function(observations, num_groups, counts_per_category, blume_capel_stats, pairwise_stats, num_categories, main_alpha, main_beta, pairwise_scale, pairwise_scaling_factors, difference_scale, difference_selection_alpha, difference_selection_beta, difference_prior, iter, warmup, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, difference_selection, main_difference_selection, main_effect_indices, pairwise_effect_indices, target_accept, nuts_max_depth, learn_mass_matrix, projection, group_membership, group_indices, interaction_index_matrix, inclusion_probability, num_chains, nThreads, seed, update_method, hmc_num_leapfrogs, progress_type) {
    .Call(`_bgms_run_bgmCompare_parallel`, observations, num_groups, counts_per_category, blume_capel_stats, pairwise_stats, num_categories, main_alpha, main_beta, pairwise_scale, pairwise_scaling_factors, difference_scale, difference_selection_alpha, difference_selection_beta, difference_prior, iter, warmup, na_impute, missing_data_indices, is_ordinal_variable, baseline_category, difference_selection, main_difference_selection, main_effect_indices, pairwise_effect_indices, target_accept, nuts_max_depth, learn_mass_matrix, projection, group_membership, group_indices, interaction_index_matrix, inclusion_probability, num_chains, nThreads, seed, update_method, hmc_num_leapfrogs, progress_type)
}

get_explog_switch <- function() {
    .Call(`_bgms_get_explog_switch`)
}

rcpp_ieee754_exp <- function(x) {
    .Call(`_bgms_rcpp_ieee754_exp`, x)
}

rcpp_ieee754_log <- function(x) {
    .Call(`_bgms_rcpp_ieee754_log`, x)
}

.compute_ess_cpp <- function(array3d) {
    .Call(`_bgms_compute_ess_cpp`, array3d)
}

.compute_rhat_cpp <- function(array3d) {
    .Call(`_bgms_compute_rhat_cpp`, array3d)
}

.compute_indicator_ess_cpp <- function(array3d) {
    .Call(`_bgms_compute_indicator_ess_cpp`, array3d)
}

compute_conditional_ggm <- function(observations, predict_vars, precision) {
    .Call(`_bgms_compute_conditional_ggm`, observations, predict_vars, precision)
}

compute_conditional_probs <- function(observations, predict_vars, pairwise, main, num_categories, variable_type, baseline_category) {
    .Call(`_bgms_compute_conditional_probs`, observations, predict_vars, pairwise, main, num_categories, variable_type, baseline_category)
}

compute_conditional_mixed <- function(x_observations, y_observations, predict_vars, pairwise_disc, pairwise_cross, pairwise_cont, mux, muy, num_categories, variable_type, baseline_category) {
    .Call(`_bgms_compute_conditional_mixed`, x_observations, y_observations, predict_vars, pairwise_disc, pairwise_cross, pairwise_cont, mux, muy, num_categories, variable_type, baseline_category)
}

sample_omrf_gibbs <- function(num_states, num_variables, num_categories, pairwise, main, iter, seed) {
    .Call(`_bgms_sample_omrf_gibbs`, num_states, num_variables, num_categories, pairwise, main, iter, seed)
}

sample_bcomrf_gibbs <- function(num_states, num_variables, num_categories, pairwise, main, variable_type_r, baseline_category, iter, seed) {
    .Call(`_bgms_sample_bcomrf_gibbs`, num_states, num_variables, num_categories, pairwise, main, variable_type_r, baseline_category, iter, seed)
}

sample_ggm_direct <- function(num_states, precision, means, seed) {
    .Call(`_bgms_sample_ggm_direct`, num_states, precision, means, seed)
}

run_simulation_parallel <- function(pairwise_samples, main_samples, draw_indices, num_states, num_variables, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type) {
    .Call(`_bgms_run_simulation_parallel`, pairwise_samples, main_samples, draw_indices, num_states, num_variables, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type)
}

run_ggm_simulation_parallel <- function(pairwise_samples, main_samples, draw_indices, num_states, num_variables, means, nThreads, seed, progress_type) {
    .Call(`_bgms_run_ggm_simulation_parallel`, pairwise_samples, main_samples, draw_indices, num_states, num_variables, means, nThreads, seed, progress_type)
}

sample_mixed_mrf_gibbs <- function(num_states, pairwise_disc_r, pairwise_cross_r, pairwise_cont_r, mux_r, muy_r, num_categories_r, variable_type_r, baseline_category_r, iter, seed) {
    .Call(`_bgms_sample_mixed_mrf_gibbs`, num_states, pairwise_disc_r, pairwise_cross_r, pairwise_cont_r, mux_r, muy_r, num_categories_r, variable_type_r, baseline_category_r, iter, seed)
}

run_mixed_simulation_parallel <- function(mux_samples, disc_samples, muy_samples, cont_samples, cross_samples, draw_indices, num_states, p, q, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type) {
    .Call(`_bgms_run_mixed_simulation_parallel`, mux_samples, disc_samples, muy_samples, cont_samples, cross_samples, draw_indices, num_states, p, q, num_categories, variable_type_r, baseline_category, iter, nThreads, seed, progress_type)
}

sample_ggm <- function(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior = "Bernoulli", beta_bernoulli_alpha = 1.0, beta_bernoulli_beta = 1.0, beta_bernoulli_alpha_between = 1.0, beta_bernoulli_beta_between = 1.0, dirichlet_alpha = 1.0, lambda = 1.0, na_impute = FALSE, missing_index_nullable = NULL, pairwise_prior = "cauchy", pairwise_scale = 2.5, blasso_shape = 2.0, blasso_rate = 0.1, diagonal_prior = "exponential", diagonal_prior_rate = 1.0) {
    .Call(`_bgms_sample_ggm`, inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, na_impute, missing_index_nullable, pairwise_prior, pairwise_scale, blasso_shape, blasso_rate, diagonal_prior, diagonal_prior_rate)
}

sample_mixed_mrf <- function(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior = "Bernoulli", beta_bernoulli_alpha = 1.0, beta_bernoulli_beta = 1.0, beta_bernoulli_alpha_between = 1.0, beta_bernoulli_beta_between = 1.0, dirichlet_alpha = 1.0, lambda = 1.0, sampler_type = "mh", target_acceptance = 0.80, max_tree_depth = 10L, num_leapfrogs = 100L, na_impute = FALSE, missing_index_discrete_nullable = NULL, missing_index_continuous_nullable = NULL) {
    .Call(`_bgms_sample_mixed_mrf`, inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, seed, no_threads, progress_type, edge_prior, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, sampler_type, target_acceptance, max_tree_depth, num_leapfrogs, na_impute, missing_index_discrete_nullable, missing_index_continuous_nullable)
}

sample_omrf <- function(inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, sampler_type, seed, no_threads, progress_type, edge_prior = "Bernoulli", na_impute = FALSE, missing_index_nullable = NULL, beta_bernoulli_alpha = 1.0, beta_bernoulli_beta = 1.0, beta_bernoulli_alpha_between = 1.0, beta_bernoulli_beta_between = 1.0, dirichlet_alpha = 1.0, lambda = 1.0, target_acceptance = 0.8, max_tree_depth = 10L, num_leapfrogs = 10L, pairwise_scaling_factors_nullable = NULL) {
    .Call(`_bgms_sample_omrf`, inputFromR, prior_inclusion_prob, initial_edge_indicators, no_iter, no_warmup, no_chains, edge_selection, sampler_type, seed, no_threads, progress_type, edge_prior, na_impute, missing_index_nullable, beta_bernoulli_alpha, beta_bernoulli_beta, beta_bernoulli_alpha_between, beta_bernoulli_beta_between, dirichlet_alpha, lambda, target_acceptance, max_tree_depth, num_leapfrogs, pairwise_scaling_factors_nullable)
}

compute_Vn_mfm_sbm <- function(num_variables, dirichlet_alpha, t_max, lambda) {
    .Call(`_bgms_compute_Vn_mfm_sbm`, num_variables, dirichlet_alpha, t_max, lambda)
}

