# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_c_parallel <- function(no_persons, node, category, exp_current, rest_matrix, no_categories, thresholds, g, q) {
    .Call(`_bgms_compute_c_parallel`, no_persons, node, category, exp_current, rest_matrix, no_categories, thresholds, g, q)
}

sample_omrf_gibbs <- function(no_states, no_nodes, no_categories, interactions, thresholds, iter) {
    .Call(`_bgms_sample_omrf_gibbs`, no_states, no_nodes, no_categories, interactions, thresholds, iter)
}

em_gamma <- function(interactions, slab_var, theta, xi, no_persons) {
    .Call(`_bgms_em_gamma`, interactions, slab_var, theta, xi, no_persons)
}

em_interaction_var <- function(gamma, slab_var, theta, xi, no_persons) {
    .Call(`_bgms_em_interaction_var`, gamma, slab_var, theta, xi, no_persons)
}

compute_c_serial <- function(no_persons, node, category, exp_current, rest_matrix, no_categories, thresholds, g, q) {
    .Call(`_bgms_compute_c_serial`, no_persons, node, category, exp_current, rest_matrix, no_categories, thresholds, g, q)
}

log_pseudolikelihood_ratio_serial <- function(interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix) {
    .Call(`_bgms_log_pseudolikelihood_ratio_serial`, interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix)
}

log_pseudolikelihood_ratio <- function(interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix, parallel) {
    .Call(`_bgms_log_pseudolikelihood_ratio`, interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix, parallel)
}

create_rest_matrix <- function(no_persons, no_nodes, observations, interactions) {
    .Call(`_bgms_create_rest_matrix`, no_persons, no_nodes, observations, interactions)
}

gibbs_sampler <- function(observations, gamma, interactions, thresholds, no_categories, interaction_prior, cauchy_scale, unit_info, proposal_sd, Index, iter, burnin, n_cat_obs, threshold_alpha, threshold_beta, save = FALSE, display_progress = FALSE, parallel = FALSE) {
    .Call(`_bgms_gibbs_sampler`, observations, gamma, interactions, thresholds, no_categories, interaction_prior, cauchy_scale, unit_info, proposal_sd, Index, iter, burnin, n_cat_obs, threshold_alpha, threshold_beta, save, display_progress, parallel)
}

gradient_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_gradient_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_gradient_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

gradient_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_gradient_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_bgms_gradient_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

gradient_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call(`_bgms_gradient_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_hessian_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

hessian_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_bgms_hessian_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

hessian_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call(`_bgms_hessian_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_crossparameters <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_crossparameters`, interactions, thresholds, observations, no_categories)
}

log_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_log_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

log_unnormalized_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha, threshold_beta)
}

log_unnormalized_pseudoposterior_cauchy <- function(interactions, thresholds, observations, cauchy_scale, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_cauchy`, interactions, thresholds, observations, cauchy_scale, no_categories, threshold_alpha, threshold_beta)
}

emvs_log_unnormalized_pseudoposterior <- function(interactions, thresholds, observations, no_categories, xi, slab_var, theta = 0.5, hierarchical = FALSE, indicator_alpha = 1.0, indicator_beta = 1.0, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_emvs_log_unnormalized_pseudoposterior`, interactions, thresholds, observations, no_categories, xi, slab_var, theta, hierarchical, indicator_alpha, indicator_beta, threshold_alpha, threshold_beta)
}

log_pseudolikelihood_ratio_parallel <- function(interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix) {
    .Call(`_bgms_log_pseudolikelihood_ratio_parallel`, interactions, thresholds, observations, no_categories, no_persons, node1, node2, proposed_state, current_state, rest_matrix)
}

start_profiler <- function(str) {
    .Call(`_bgms_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_bgms_stop_profiler`)
}

